version: 0.{build}
skip_tags: true
cache: C:\Users\appveyor\AppData\Local\NuGet\Cache
build_script:
- git submodule update --init --recursive
- powershell "& .\scripts\replace-version.ps1"
- scripts\make.bat
test: off
artifacts:
- path: output/*
  name: diego-windows
deploy:
- provider: S3
  access_key_id: AKIAJ3M5ORCAISPRT22Q
  secret_access_key:
    secure: lMbaCusTBxZpIbSzoILyHMBkz+sVH7EwgAqI3sAVYAM92OcIzlzq1IzcB8MmnRvZ
  region: us-east-1
  bucket: diego-windows-release
  artifact: diego-windows
  set_public: true
  on:
    branch: master
clone_folder: c:\diego-windows-release
branches:
  only:
  - master
  - /appveyor/
