---
platform: linux
image: docker:///pivotalgreenhouse/ruby
inputs:
  - name: diego-windows-msi
  - name: msi-file
  - name: diego-release
run:
  path: diego-windows-msi/scripts/release.rb
params:
  GITHUB_TOKEN:
  
